import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API endpoint for chat messages
  app.post("/api/chat", async (req, res) => {
    try {
      const { messages, customApiKey } = req.body;
      if (!messages || !Array.isArray(messages)) {
        return res.status(400).json({ error: "Messages array is required." });
      }

      const apiKey = (customApiKey && customApiKey.trim() !== "") ? customApiKey : process.env.GEMINI_API_KEY;
      if (!apiKey || apiKey === "MY_GEMINI_API_KEY" || apiKey.trim() === "") {
        return res.status(500).json({
          error: "GEMINI_API_KEY is missing. Please select an active key or configure it in your AI Studio Secrets panel."
        });
      }

      // Initialize GoogleGenAI SDK correctly
      const ai = new GoogleGenAI({
        apiKey: apiKey,
        httpOptions: {
          headers: {
            'User-Agent': 'aistudio-build',
          }
        }
      });

      // Map messages: roles are strictly "user" or "model"
      const contents = messages.map((m: any) => ({
        role: m.role === "assistant" ? "model" : "user",
        parts: [{ text: m.content }]
      }));

      // Try multiple certified models in sequence in case of 503 high-demand limits
      const modelsToTry = ["gemini-3.1-flash-lite", "gemini-3.5-flash", "gemini-flash-latest"];
      let response = null;
      let lastError = null;

      for (const modelName of modelsToTry) {
        try {
          console.log(`Attempting generation with model: ${modelName}`);
          response = await ai.models.generateContent({
            model: modelName,
            contents,
            config: {
              systemInstruction: "You are ChatGPT, a helpful AI chatbot. Respond in Hindi, English, Hinglish or the language matching the user's input. Provide useful, concise yet comprehensive markdown-supported responses with a friendly iOS-style assistant voice. Keep formatting clean with bullet lists, lists, or code blocks where appropriate."
            }
          });
          if (response) {
            console.log(`Successfully generated content using: ${modelName}`);
            break;
          }
        } catch (err: any) {
          lastError = err;
          console.warn(`Model ${modelName} call failed:`, err.message || err);
          // If it's a 503 or overload, continue immediately. Otherwise, continue trying fallback.
        }
      }

      if (!response) {
        throw lastError || new Error("All recommended AI models are experiencing high demand. Please try again soon.");
      }

      const reply = response.text || "No response generated by model.";
      res.json({ reply });
    } catch (error: any) {
      console.error("Gemini API server side error:", error);
      res.status(500).json({ error: error.message || "An error occurred with Gemini." });
    }
  });

  // Vite integration
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server listening on port ${PORT}`);
  });
}

startServer();
